spring:

  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 3600
      chain:
        cache: true
        enabled: true
        compressed: true

      static-locations: classpath:/static/

  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 19980208gp
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: 192.168.26.166
    port: 6379
    database: 0
    timeout: 10000ms

    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 8
        min-idle: 5
    password: 19980208gp
  rabbitmq:
    host: 192.168.26.169
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0




mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xxxx.seckill.pojo
logging:
  level:
    com.xxxx.seckill.mapper: debug
